name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}
          release-type: node
          package-name: release-please-action
          pull-request-title-pattern: 'chore: v${version}'
